Select Codigo_Do_Produto, Count(*) AS NUMERO_DE_VENDAS From Itens_Notas_Fiscais Where Quantidade = '99' AND Codigo_Do_Produto = '1101035' GROUP BY codigo_do_produto;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS NUMERO_DE_VENDAS FROM ITENS_NOTAS_FISCAIS GROUP BY CODIGO_DO_PRODUTO ORDER BY NUMERO_DE_VENDAS DESC;

--PROFESSOR:
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO ORDER BY SUM(QUANTIDADE) DESC;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS LITROS_VENDIDOS FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) >= 394000 ORDER BY LITROS_VENDIDOS DESC;

--PROFESSOR:
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;

SELECT * FROM NOTAS_FISCAIS
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS LITROS_VENDIDOS FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) >= 394000 ORDER BY LITROS_VENDIDOS DESC;



SELECT NOME, ESTADO,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTES_GRANDES'
      WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'CLIENTES_MEDIOS'
      WHEN LIMITE_DE_CREDITO < 110000 THEN 'CLIENTES_PEQUENOS'
      END) AS CATEGORIA_DE_CLIENTE
FROM TABELA_DE_CLIENTES ORDER BY LIMITE_DE_CREDITO DESC;

SELECT DISTINCT ESTADO FROM TABELA_DE_CLIENTES;