CREATE TABLE TB_VENDEDORES(
MATRICULA CHAR(8),
NOME CHAR(60),
COMISSÃO CHAR (5),
DATA_ADMISSAO DATE,
DE_FERIAS CHAR(3)
);

SELECT * FROM TB_VENDEDORES;

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY (MATRICULA);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, COMISSÃO, DATA_ADMISSAO, DE_FERIAS)
VALUES('00235', 'Márcio Almeida', '8%', TO_DATE('15/08/2014', 'DD/MM/YYYY'),'NAO');

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, COMISSÃO, DATA_ADMISSAO, DE_FERIAS)
VALUES('00236', 'Cláudia Morais', '8%', TO_DATE('17/09/2013', 'DD/MM/YYYY'),'SIM');

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, COMISSÃO, DATA_ADMISSAO, DE_FERIAS)
VALUES('00237', 'Roberta Martins', '11%', TO_DATE('18/03/2017', 'DD/MM/YYYY'),'SIM');

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, COMISSÃO, DATA_ADMISSAO, DE_FERIAS)
VALUES('00238', 'Péricles Alves', '11%', TO_DATE('21/08/2016', 'DD/MM/YYYY'),'NAO');

SELECT * FROM TB_CLIENTES;

ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (CPF);

ALTER TABLE TB_CLIENTES ADD DATA_NASCIMENTO DATE;

INSERT INTO TB_CLIENTES (
    CPF, NOME, ENDERECO1, ENDERECO2, 
    BAIRRO, CIDADE, ESTADO, CEP, IDADE, 
    SEXO, LIMITE_CREDITO, VOLUME_COMPRA, 
    PRIMEIRA_COMPRA, DATA_NASCIMENTO
) VALUES (
    '00388934777', 'João da Silva', 'Rua Projetada A número 10', 
    NULL , 'VILA ROMAN', 'TRÊS RIOS', 'RJ', '22222222', 53, 'M', 
    20000.00, 2000, 0, TO_DATE('12/10/1965','MM/DD/YYYY')
);

UPDATE TB_CLIENTES SET DATA_NASCIMENTO = '12/10/1965'
WHERE (CPF = 00388934777)



